# Generated by Django 3.1.7 on 2021-03-23 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custName', models.CharField(max_length=20)),
                ('userName', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
                ('phoneNumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empName', models.CharField(max_length=20)),
                ('userName', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
                ('phoneNumber', models.IntegerField()),
                ('isAdmin', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='HotelName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='HotelRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=10)),
                ('count', models.IntegerField()),
                ('hotelId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.hotelname')),
            ],
        ),
        migrations.CreateModel(
            name='HotelEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('userName', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
                ('phoneNumber', models.IntegerField()),
                ('hotelId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.hotelname')),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('available', models.CharField(max_length=1)),
                ('custId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.customer')),
                ('roomId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.hotelroom')),
            ],
        ),
    ]
