# Generated by Django 3.2.1 on 2021-05-06 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_chat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
