# Generated by Django 3.2.2 on 2021-05-26 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_auto_20210527_0521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='cancelled',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='status',
        ),
    ]
