# Generated by Django 3.1.7 on 2021-04-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_auto_20210407_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelroom',
            name='hotelId',
        ),
        migrations.AddField(
            model_name='hotelroom',
            name='Room_number',
            field=models.IntegerField(default=101),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotelroom',
            name='capacity',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
