# Generated by Django 3.2.2 on 2021-05-26 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_auto_20210527_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='cancel',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('1', 'Booked'), ('2', 'Cancelled')], default=1, max_length=15),
            preserve_default=False,
        ),
    ]
