# Generated by Django 3.2.2 on 2021-06-05 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_auto_20210604_1402'),
        ('myApp', '0005_pnumber'),
    ]

    operations = [
    ]
