# Generated by Django 3.1.7 on 2021-04-13 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='country',
            field=models.CharField(default='India', max_length=20),
        ),
    ]
