# Generated by Django 3.2.2 on 2021-05-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='posted_at',
            field=models.DateTimeField(),
        ),
    ]
